Django app
=========
My notes on creating Django app

Goal
-------
* Reusable in other projects.
* Easily duplicate the environment.
* Share common top level namespace.

Namespace package
-------------------------------
Use fez.djangoskel_ to create namespace package. 

```console
$ easy install fez.djangoskel
$ paster create -t django_namespace_app
```

More on [[Python Namespace]].

This is Link_ to click.

.. _fez.djangoskel: http://pypi.python.org/pypi/fez.djangoskel/
.. _Link: http://www.djangoproject.com/