Drupal Quirks
===========
A collection of Drupal quirks I have found.

Form API theme function/template can only accept one argument - form
---------------------------------------------------------------------------------------------------------
I thought I can do this:-

```php5
<?php
function custom_theme($existing, $type, $theme, $path) {
  return array(
    'my_form_id' => array(
      'arguments' => array('node' => NULL, 'messages' => array()),
      'template' => 'my-form-id',
    ),
  );
}

function custom_path_to_page($node) {
  $messages = array();
  return drupal_get_form('my_form_id', $node, $messages);
}
?>
```
and get both ``$node`` and ``$messages`` in my template file. Turn out I can't. Theme function (or template) for form can only accept one argument - form. For any extra data that I need to pass to the template, I have to use the value type.

 http://drupal.org/node/748004